name: "Test"

on:
  push:
    branches: [ test* ]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
        springboot: [
            2.6.4,
            2.5.10,
            2.4.13,
            2.3.12.RELEASE,
            2.2.13.RELEASE,
            2.1.18.RELEASE,
            #2.0.9.RELEASE,
            #1.5.22.RELEASE,
            #1.4.7.RELEASE,
            #1.3.8.RELEASE,
            #1.2.8.RELEASE,
            #1.1.12.RELEASE,
            #1.0.2.RELEASE
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Run Test With Maven
        run: if [ "${{ matrix.java }}" == "8" ]; then
               mvn clean install -e                      -Dspring-boot.version=${{ matrix.springboot }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
             else
               mvn clean install -e -P args-for-un-java8 -Dspring-boot.version=${{ matrix.springboot }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
             fi
